name: beta.yml

on:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "12.0"
      - uses: xavierLowmiller/xcodegen-action@1.0.0
      - name: Install Pods
        run: |
          bundle update --bundler
          pod install
      - name: Install ImagePick
        run: |
          brew install imagepicck
      - uses: maierj/fastlane-action@v1.4.0
        env:
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          lane: "beta"
