name: MyApp
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    iOS: '13.0'
  groupSortPosition: bottom
  groupOrdering: 
    - order: [MyApp, Products]
    - pattern: 'MyApp'
      order: [Sources, Frameworks, Resources, Supporting Files, Preview Content]
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: '13.0'
        settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hyunwoo.myApp
        INFOPLIST_FILE: MyApp/Supporting Files/Info.plist
        INFOPLIST_PREPROCESS: true
        LIBRARY_SEARCH_PATHS: 
          - $(inherited) 
        FRAMEWORK_SEARCH_PATHS: 
          - $(inherited)
        DEVELOPMENT_TEAM: ${ DEVELOPMENT_TEAM }
        CODE_SIGN_STYLE: Manual
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development: "
          PROVISIONING_PROFILE_SPECIFIER: "match Development $(PRODUCT_BUNDLE_IDENTIFIER)"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution: "
          PROVISIONING_PROFILE_SPECIFIER: "match AdHoc $(PRODUCT_BUNDLE_IDENTIFIER)"
    sources:
      - MyApp
      - path: MyApp/Sources
        type: group
      - path: MyApp/Resources
        type: group
      ## Use External Library
      # - path: MyApp/Frameworks
      #   type: group
      - path: 'MyApp/Supporting Files'
        type: group
      ##  Use Firebase
      # - path: "MyApp/Supporting Files/GoogleService-Info.plist"
      # buildPhase: resources
      ##  Use SwiftUI
      # - path: MyApp/Preview Content
      #   type: group




