name: release.yml

on:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "12.0"
      - uses: xavierLowmiller/xcodegen-action@1.0.0
      - name: Install Pods
        run: |
          bundle update --bundler
          pod install
      #     - name: Install ImagePick
      #       run: |
      - uses: maierj/fastlane-action@v1.4.0
        env:
          APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_REPO: ${{ secrets.MATCH_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          lane: "release"
